Ext.define('TestApp.view.Curtaincontainer',{
	extend:'Ext.form.Panel',
	alias:'widget.curtaincontainer',
	fullscreen:true,
	scrollable:'vertical', 
	initialize:function(){
		this.callParent();
		var backBtn = {
			xtype:'button',
			ui:'back',
			text:'首页',
			handler:this.onBackButtonTap,
			scope:this
		};
		var topToolbar = {
			xtype:'toolbar',
			title:'窗帘控制',
			docked:'top',
			items:[
				backBtn
			]
		};
		var on = {
			xtype:'button',
			text:'一键开启',
			handler:this.fon,
			scope:this
		};
		var off = {
			xtype:'button',
			text:'一键关闭',
			handler:this.foff,
			scope:this
		}
		var bottomToolbar = {
			xtype:'toolbar',
			docked:'bottom',
			items:[
				on,
				{
					xtype:'spacer'
				},
				off
			]
		};
		var r1 = {
			xtype:'fieldset',
			id:'ctfs1',
			title:'办公室1',
			items:[
			{
				xtype:'radiofield',
				name:'office1',
				value:'up',
				label:'上升',
				listeners:{
					check:{
						fn:this.changecheck,
						scope:this
					}
				}
			},
			{
				xtype:'radiofield',
				name:'office1',
				value:'stop',
				label:'暂停',
				checked:true,
				listeners:{
					check:{
						fn:this.changecheck,
						scope:this
					}
				}
			},
			{
				xtype:'radiofield',
				name:'office1',
				value:'down',
				label:'下降',
				listeners:{
					check:{
						fn:this.changecheck,
						scope:this
					}
				}
			}
			]
		};
		var r2 = {
			xtype:'fieldset',
			id:'ctfs2',
			title:'办公室2',
			items:[
			{
				xtype:'radiofield',
				name:'office2',
				value:'up',
				label:'上升',
				listeners:{
					check:{
						fn:this.changecheck,
						scope:this
					}
				}
			},
			{
				xtype:'radiofield',
				name:'office2',
				value:'stop',
				label:'暂停',
				checked:true,
				listeners:{
					check:{
						fn:this.changecheck,
						scope:this
					}
				}
			},
			{
				xtype:'radiofield',
				name:'office2',
				value:'down',
				label:'下降',
				listeners:{
					check:{
						fn:this.changecheck,
						scope:this
					}
				}
			}
			]
		};
		var r3 = {
			xtype:'fieldset',
			id:'ctfs3',
			title:'办公室3',
			items:[
			{
				xtype:'radiofield',
				name:'office3',
				value:'up',
				label:'上升',
				listeners:{
					check:{
						fn:this.changecheck,
						scope:this
					}
				}
			},
			{
				xtype:'radiofield',
				name:'office3',
				value:'stop',
				label:'暂停',
				checked:true,
				listeners:{
					check:{
						fn:this.changecheck,
						scope:this
					}
				}
			},
			{
				xtype:'radiofield',
				name:'office3',
				value:'down',
				label:'下降',
				checked:true,
				listeners:{
					check:{
						fn:this.changecheck,
						scope:this
					}
				}
			}
			]
		};
		var r4 = {
			xtype:'fieldset',
			id:'ctfs4',
			title:'办公室4',
			items:[
			{
				xtype:'radiofield',
				name:'office4',
				value:'up',
				label:'上升',
				listeners:{
					check:{
						fn:this.changecheck,
						scope:this
					}
				}
			},
			{
				xtype:'radiofield',
				name:'office4',
				value:'stop',
				label:'暂停',
				checked:true,
				listeners:{
					check:{
						fn:this.changecheck,
						scope:this
					}
				}
			},
			{
				xtype:'radiofield',
				name:'office4',
				value:'down',
				label:'下降',
				listeners:{
					check:{
						fn:this.changecheck,
						scope:this
					}
				}
			}
			]
		};
		var r5 = {
			xtype:'fieldset',
			id:'ctfs5',
			title:'办公室5',
			items:[
			{
				xtype:'radiofield',
				name:'office5',
				value:'up',
				label:'上升',
				listeners:{
					check:{
						fn:this.changecheck,
						scope:this
					}
				}
			},
			{
				xtype:'radiofield',
				name:'office5',
				value:'stop',
				label:'暂停',
				checked:true,
				listeners:{
					check:{
						fn:this.changecheck,
						scope:this
					}
				}
			},
			{
				xtype:'radiofield',
				name:'office5',
				value:'down',
				label:'下降',
				listeners:{
					check:{
						fn:this.changecheck,
						scope:this
					}
				}
			}
			]
		};
		this.add([
			topToolbar,
			{
				xtype:'fieldset',
				autoScroll:true,
				items:[
					r1,r2,r3,r4,r5
				]
			
			},
			bottomToolbar
		]);
	},
	onBackButtonTap: function() {
        console.log('backToHomeCommand');
        this.fireEvent("backToHomeCommand", this);
    },
    changecheck:function(me,e,opts){
    	console.log("radio.name="+me.getName()+",radio.value="+me.getValue());
    	this.fireEvent('changecheck',this,me);
    }
})